<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="2" file="scan_utils_tests.py" name="scan_utils_tests.TestCheckOpenPort-20201130183011" skipped="0" tests="2" time="0.510" timestamp="2020-11-30T18:30:11">
	<testcase classname="scan_utils_tests.TestCheckOpenPort" name="test_check_closed_port" time="0.260" timestamp="2020-11-30T18:30:11">
		<failure message="&lt;DictProxy object, typeid 'dict' at 0x7fcbd8ddfb38&gt; != {'3280': False}" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project3/src/unittest/python/scan_utils_tests.py", line 28, in test_check_closed_port
    self.assertEqual(test_dictionary, ports)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: <DictProxy object, typeid 'dict' at 0x7fcbd8ddfb38> != {'3280': False}
]]>		</failure>
	</testcase>
	<testcase classname="scan_utils_tests.TestCheckOpenPort" name="test_check_open_port" time="0.251" timestamp="2020-11-30T18:30:11">
		<failure message="&lt;DictProxy object, typeid 'dict' at 0x7fcbd8d0c908&gt; != {'3280': True}" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project3/src/unittest/python/scan_utils_tests.py", line 41, in test_check_open_port
    self.assertEqual(test_dictionary, ports)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: <DictProxy object, typeid 'dict' at 0x7fcbd8d0c908> != {'3280': True}
]]>		</failure>
	</testcase>
</testsuite>
