<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="scan_utils_tests.py" name="scan_utils_tests.TestHandleScanConnection-20201130184629" skipped="0" tests="1" time="0.785" timestamp="2020-11-30T18:46:31">
	<testcase classname="scan_utils_tests.TestHandleScanConnection" name="test_handle_scan_connection" time="0.785" timestamp="2020-11-30T18:46:31">
		<error message="[Errno 2] No such file or directory" type="FileNotFoundError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project3/src/unittest/python/scan_utils_tests.py", line 66, in test_handle_scan_connection
    OUTPUT = PARENT_CONNECTION.recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 881, in RebuildProxy
    return func(token, serializer, incref=incref, **kwds)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 731, in __init__
    self._incref()
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 785, in _incref
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
]]>		</error>
	</testcase>
</testsuite>
